baseURL: "https://magnusnosnes.netlify.app/"
languageCode: "en-us"
title: "Hugo Profile"
theme: "hugo-profile"
Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1


    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Dr. Magnus Nygård Osnes"
  description: This is my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # light

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Magnus Nygård Osnes"
    subtitle: "I am a biostatistican or maybe a bioinformatician"
    content: "I have worked with multiple bacterias and viruses and apply and develop new methods to analyse them"
    image: /images/me.png
    button:
      enable: true
      name: "Resume"
      url: "https://www.linkedin.com/in/magnus-nyg%C3%A5rd-osnes-22655922b/"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/magnusnosnes
        - icon: fab fa-twitter
          url: https://twitter.com/MagnusOsnes
      customIcons:
        # - icon: /fav.png
        #   url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: ""
    content: |-
      I am a computational biologist with a passion for development of new methods. I have a background in statistics and mathematics,
      and I have a strong interest in the intersection of technology and biology. I am currently working as a postdoc at the Norwegian Institute of Public Health. 

      I am currently working on a project where we try to figure out things that contribute to penicillin resistance in bacteria. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "R"
        - "Python"
        - "BUGS"
        - "Nimble"
        - "Bayesian statistics"
        - "Shiny, blogdown and hugo"

  # # Experience
  # experience:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - job: "Postdoc"
  #       company: "Norwegian Institute of Public Health"
  #       companyUrl: "https://example.com"
  #       date: "May 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working on a project where we try to figure out things that contribute to penicillin resistance in bacteria."
  #           
  # 
  #     - job: "Doctoral candidate"
  #       company: "Norwegian Institute of Public Health"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2018 - May 2022"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I did my PhD at the Norwegian Institute of Public Health.
  #       content: |
  #         Genome epidemiology of Neisseria gonorrhoeae and SARS-CoV-2 - Strain dynamics from the level of individuals to global dissemination
  #         - Method development.
  #         - Statistical and genomic analyses. 
  #         - Phylogenetics.   


  # # Education
  # education:
  #   enable: true
  #   # title: "Custom Name"
  #   # index: true
  #   items:
  #     - title: "Master in Ecology and Evolution"
  #       school:
  #         name: "University of Oslo"
  #         url: "https://example.org"
  #       date: "2015 - 2018"
  #       content: |-
  #         "A hierarchical Bayesian state space model for fluctuating rodent populations, with application to the populations at Finse, Norway"
  #           - Bayesian statistical model development. 
  #           
  #     - title: "Bachelor of Science"
  #       school:
  #         name: "University of Oslo"
  #         url: "https://example.org"
  #       date: "2009 - 2013"
  #       content: |-
  #         I combined courses from biology, mathemathics and statistics into a bachlor degree in science. 
  #       featuredLink:
  #         enable: true
  #         name: "My academic record"
  #         url: "https://example.com"
  #     - title: "Lillestrøm Videregående Skole"
  #       school:
  #         name: "Allmenn fag"
  #         url: "https://example.org"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Disentangling penicillin resistance and compensatory adaption in pneumococci by combining genomics and molecular microbiology
        content: Here we use genome wide association procedures and machine learning to learn more about the mechanisms causing penicillin resistance in Streptococcus pneumoniae.
        image: /images/projects/Placeholder_pneumococci.png
        featured:
          name: Project website
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: The inter-continental population dynamics of Neisseria gonorrhoeae
        content: Here we investigate the global transmission dynamics of Neisseria gonorrhoeae from 2015 - 2018.
        image: /images/projects/10000_genomes.png
        featured:
          name: Project website
          link: https://magnusnosnes.github.io/10000_Ngon_genomes/
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: LineageHomology
        content: LineageHomology uses phylogenies with reconstructed ancestral states to define groups of phylogenetic tips that have gained their states through homologous inheritance or de novo acquisition.
        image: /images/projects/LineageHomology.png
        featured:
          name: Github
          link: https://github.com/magnusnosnes/LineageHomology
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2
            
      - title: Doctoral thesis
        content: Genome epidemiology of Neisseria gonorrhoeae and SARS-CoV-2 Strain dynamics from the level of individuals to global dissemination.
        image: /images/projects/Doctoral.jpeg
        featured:
          name: Doctoral     thesis
          link: https://www.duo.uio.no/handle/10852/93907
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2
                        
      - title: Master thesis
        content: A hierarchical Bayesian state space model for fluctuating rodent populations, with application to the populations at Finse, Norway
        image: /images/projects/Master_thesis.png
        featured:
          name: Master thesis
          link: https://www.duo.uio.no/handle/10852/61662
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2


  #Contact
  contact:
    enable: true
    title: "Get in touch"
    content: 
    email: magnusnosnes@gmail.com
    btnName: Mail me

  footer:
    recentPosts: true
    socialNetworks:
      github: https://github.com/magnusnosnes
      linkedin: https://www.linkedin.com/in/magnus-nyg%C3%A5rd-osnes-22655922b
      twitter: https://twitter.com/MagnusOsnes
